# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: startstream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='startstream.proto',
  package='startstream',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11startstream.proto\x12\x0bstartstream\"!\n\x0e\x43ommandRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\nCommandAck\x12\x0f\n\x07message\x18\x01 \x01(\t2[\n\x12\x43ommandInterpreter\x12\x45\n\x0bGiveCommand\x12\x1b.startstream.CommandRequest\x1a\x17.startstream.CommandAck\"\x00\x62\x06proto3'
)




_COMMANDREQUEST = _descriptor.Descriptor(
  name='CommandRequest',
  full_name='startstream.CommandRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='startstream.CommandRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=67,
)


_COMMANDACK = _descriptor.Descriptor(
  name='CommandAck',
  full_name='startstream.CommandAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='startstream.CommandAck.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['CommandRequest'] = _COMMANDREQUEST
DESCRIPTOR.message_types_by_name['CommandAck'] = _COMMANDACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommandRequest = _reflection.GeneratedProtocolMessageType('CommandRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDREQUEST,
  '__module__' : 'startstream_pb2'
  # @@protoc_insertion_point(class_scope:startstream.CommandRequest)
  })
_sym_db.RegisterMessage(CommandRequest)

CommandAck = _reflection.GeneratedProtocolMessageType('CommandAck', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDACK,
  '__module__' : 'startstream_pb2'
  # @@protoc_insertion_point(class_scope:startstream.CommandAck)
  })
_sym_db.RegisterMessage(CommandAck)



_COMMANDINTERPRETER = _descriptor.ServiceDescriptor(
  name='CommandInterpreter',
  full_name='startstream.CommandInterpreter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=100,
  serialized_end=191,
  methods=[
  _descriptor.MethodDescriptor(
    name='GiveCommand',
    full_name='startstream.CommandInterpreter.GiveCommand',
    index=0,
    containing_service=None,
    input_type=_COMMANDREQUEST,
    output_type=_COMMANDACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMMANDINTERPRETER)

DESCRIPTOR.services_by_name['CommandInterpreter'] = _COMMANDINTERPRETER

# @@protoc_insertion_point(module_scope)
