# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buffer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='buffer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x62uffer.proto\"\x15\n\x04Info\x12\r\n\x05hello\x18\x01 \x01(\t\"#\n\x0cSend_Request\x12\x13\n\x04send\x18\x02 \x01(\x0b\x32\x05.Info\"\"\n\x10Request_Response\x12\x0e\n\x06result\x18\x03 \x01(\t2>\n\x10Response_Service\x12*\n\x04Info\x12\r.Send_Request\x1a\x11.Request_Response\"\x00\x62\x06proto3'
)




_INFO = _descriptor.Descriptor(
  name='Info',
  full_name='Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hello', full_name='Info.hello', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=37,
)


_SEND_REQUEST = _descriptor.Descriptor(
  name='Send_Request',
  full_name='Send_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='send', full_name='Send_Request.send', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=74,
)


_REQUEST_RESPONSE = _descriptor.Descriptor(
  name='Request_Response',
  full_name='Request_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='Request_Response.result', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=110,
)

_SEND_REQUEST.fields_by_name['send'].message_type = _INFO
DESCRIPTOR.message_types_by_name['Info'] = _INFO
DESCRIPTOR.message_types_by_name['Send_Request'] = _SEND_REQUEST
DESCRIPTOR.message_types_by_name['Request_Response'] = _REQUEST_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), {
  'DESCRIPTOR' : _INFO,
  '__module__' : 'buffer_pb2'
  # @@protoc_insertion_point(class_scope:Info)
  })
_sym_db.RegisterMessage(Info)

Send_Request = _reflection.GeneratedProtocolMessageType('Send_Request', (_message.Message,), {
  'DESCRIPTOR' : _SEND_REQUEST,
  '__module__' : 'buffer_pb2'
  # @@protoc_insertion_point(class_scope:Send_Request)
  })
_sym_db.RegisterMessage(Send_Request)

Request_Response = _reflection.GeneratedProtocolMessageType('Request_Response', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST_RESPONSE,
  '__module__' : 'buffer_pb2'
  # @@protoc_insertion_point(class_scope:Request_Response)
  })
_sym_db.RegisterMessage(Request_Response)



_RESPONSE_SERVICE = _descriptor.ServiceDescriptor(
  name='Response_Service',
  full_name='Response_Service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=112,
  serialized_end=174,
  methods=[
  _descriptor.MethodDescriptor(
    name='Info',
    full_name='Response_Service.Info',
    index=0,
    containing_service=None,
    input_type=_SEND_REQUEST,
    output_type=_REQUEST_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RESPONSE_SERVICE)

DESCRIPTOR.services_by_name['Response_Service'] = _RESPONSE_SERVICE

# @@protoc_insertion_point(module_scope)
